// Code generated by Tndr(t1) - DO NOT EDIT.

// Tndr(t1): version: v0.0.3

package i

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/tndr"
import "context"
import "io"
import "bytes"

func DashboardGaugeColor() t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var1 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var1 == nil {
			t1_7745c5c3_Var1 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<svg fill=\"current-color\" width=\"800px\" height=\"800px\" viewBox=\"0 0 24 24\" id=\"dashboard-alt-2\" xmlns=\"http://www.w3.org/2000/svg\" class=\"icon multi-color\"><path id=\"secondary-fill\" d=\"M20.74,14.48A8.89,8.89,0,0,1,17.51,20H6.23A8.89,8.89,0,0,1,3,14.48a9,9,0,0,1,17.74,0Z\" style=\"fill: rgb(44, 169, 188); stroke-width: 2;\"></path><path id=\"primary-stroke\" d=\"M21,13a9,9,0,0,1-3.36,7H6.36A9,9,0,1,1,21,13Zm-9,1a1,1,0,1,0,1,1A1,1,0,0,0,12,14Zm4-5-4,6\" style=\"fill: none; stroke: rgb(0, 0, 0); stroke-linecap: round; stroke-linejoin: round; stroke-width: 2;\"></path></svg>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}
