// Code generated by Tndr(t1) - DO NOT EDIT.

// Tndr(t1): version: v0.0.3

package i

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/tndr"
import "context"
import "io"
import "bytes"

func FiletypeUnknown() t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var1 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var1 == nil {
			t1_7745c5c3_Var1 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<svg fill=\"#000000\" version=\"1.1\" id=\"Layer_1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"800px\" height=\"800px\" viewBox=\"0 0 100 100\" enable-background=\"new 0 0 100 100\" xml:space=\"preserve\"><g><path d=\"M81.232,15.138H18.769c-1.882,0-3.407,1.525-3.407,3.407v3.143c0,1.881,1.525,3.407,3.407,3.407h62.463\n		c1.881,0,3.407-1.525,3.407-3.407v-3.143C84.639,16.663,83.113,15.138,81.232,15.138z\"></path> <path d=\"M81.232,74.905H18.769c-1.882,0-3.407,1.525-3.407,3.407v3.143c0,1.881,1.525,3.407,3.407,3.407h62.463\n		c1.881,0,3.407-1.525,3.407-3.407v-3.143C84.639,76.431,83.113,74.905,81.232,74.905z\"></path> <path d=\"M84.639,58.39c0-1.882-1.525-3.407-3.407-3.407h0h0h-38.82c-1.882,0-3.407,1.525-3.407,3.407v3.143\n		c0,1.881,1.525,3.406,3.407,3.406h38.82h0c1.881,0,3.407-1.525,3.407-3.406l0-0.001v-3.141L84.639,58.39z\"></path> <path d=\"M84.639,38.577c0-1.882-1.525-3.407-3.407-3.407h0h0h-38.82c-1.882,0-3.407,1.525-3.407,3.407v3.143\n		c0,1.881,1.525,3.406,3.407,3.406h38.82h0c1.881,0,3.407-1.525,3.407-3.406c0,0,0-0.001,0-0.001v-3.141L84.639,38.577z\"></path> <path d=\"M15.361,50.008c0,0.232,0.14,0.431,0.34,0.519l-0.006,0.011l12.376,7.146c0.103,0.101,0.243,0.164,0.398,0.164\n		c0.308,0,0.556-0.247,0.565-0.553h0.003V42.722c0-0.314-0.255-0.569-0.569-0.569c-0.159,0-0.302,0.066-0.406,0.172L15.636,49.5\n		l0.014,0.024C15.481,49.622,15.361,49.798,15.361,50.008z\"></path></g></svg>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}
