// Code generated by Tndr(t1) - DO NOT EDIT.

// Tndr(t1): version: v0.0.3

package i

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/tndr"
import "context"
import "io"
import "bytes"

func Thunderf1shBitBlack() t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var1 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var1 == nil {
			t1_7745c5c3_Var1 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<svg fill=\"#000000\" height=\"800px\" width=\"800px\" version=\"1.1\" id=\"Layer_1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" viewBox=\"0 0 512 512\" xml:space=\"preserve\"><g><g><polygon points=\"111.304,0 111.304,100.174 77.913,100.174 77.913,200.348 44.522,200.348 44.522,333.913 133.565,333.913 
\n			133.565,512 200.348,512 200.348,478.609 233.739,478.609 233.739,467.478 233.739,445.217 267.13,445.217 267.13,411.826 
\n			300.522,411.826 300.522,378.435 333.913,378.435 333.913,345.043 367.304,345.043 367.304,311.652 400.696,311.652 
\n			400.696,233.739 300.522,233.739 300.522,200.348 333.913,200.348 333.913,166.957 367.304,166.957 367.304,133.565 
\n			400.696,133.565 400.696,100.174 434.087,100.174 434.087,66.783 467.478,66.783 467.478,0 		\"></polygon></g></g></svg>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}
