// Code generated by Tndr(t1) - DO NOT EDIT.

// Tndr(t1): version: v0.0.3

package signatureform

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/tndr"
import "context"
import "io"
import "bytes"

import (
	"github.com/senforsce/tndr0cean/router"
	"github.com/senforsce/tndrf1sh/web/layout/v1/meta"
)

func HTMX(cf meta.Config, c *router.Context) t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var1 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var1 == nil {
			t1_7745c5c3_Var1 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<div id=\"")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(c.Get("id:SignaturePadScid").(string)))
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\"><form id=\"test\"><canvas id=\"")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(c.Get("id:Signature").(string)))
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\"></canvas><button id=\"")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(c.Get("id:SaveSignature").(string)))
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\">")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		var t1_7745c5c3_Var2 string
		t1_7745c5c3_Var2, t1_7745c5c3_Err = t1.JoinStringErrs(c.Get("i18n:Save").(string))
		if t1_7745c5c3_Err != nil {
			return t1.Error{Err: t1_7745c5c3_Err, FileName: `owl/signatureform/sf.t1`, Line: 12, Col: 33}
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var2))
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</button></form></div>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		t1_7745c5c3_Err = Init(c).Render(ctx, t1_7745c5c3_Buffer)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		t1_7745c5c3_Err = meta.O8(cf).Render(ctx, t1_7745c5c3_Buffer)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}

func Init(c *router.Context) t1.ComponentScript {
	return t1.ComponentScript{
		Name: `__t1_Init_49d3`,
		Function: `function __t1_Init_49d3(c){//     <script src={ c.Get("path:SignaturePad").(string) } type="text/javascript"></script>

    const canvas = document.querySelector( c.Get("id:Signature").(string) });
    const save = document.querySelector( c.Get("id:SaveSignature").(string) });

    const signaturePad = new SignaturePad(canvas, 
        minWidth: 5,
        maxWidth: 10,
        penColor: "rgb(66, 133, 244)"
    });

    const signaturePad = new SignaturePad(canvas);
    signaturePad.addEventListener("endStroke", () => 
        console.log("Ended started");
        save.removeAttribute("disabled");

        // EXAMPLES
        // sen:TODO: Simple use case Of a signature form

        // Returns signature image as data URL (see https://mdn.io/todataurl for the list of possible parameters)
        signaturePad.toDataURL(); // save image as PNG
        signaturePad.toDataURL("image/jpeg"); // save image as JPEG
        signaturePad.toDataURL("image/jpeg", 0.5); // save image as JPEG with 0.5 image quality
        signaturePad.toDataURL("image/svg+xml"); // save image as SVG data url

        // Return svg string without converting to base64
        signaturePad.toSVG(); // "<svg...</svg>"
        signaturePad.toSVG(includeBackgroundColor: true}); // add background color to svg output

        // Draws signature image from data URL (mostly uses https://mdn.io/drawImage under-the-hood)
        // NOTE: This method does not populate internal data structure that represents drawn signature. Thus, after using #fromDataURL, #toData won't work properly.
        signaturePad.fromDataURL("data:image/png;base64,iVBORw0K...");

        // Draws signature image from data URL and alters it with the given options
        signaturePad.fromDataURL("data:image/png;base64,iVBORw0K...",  ratio: 1, width: 400, height: 200, xOffset: 100, yOffset: 50 });

        // Returns signature image as an array of point groups
        const data = signaturePad.toData();

        // Draws signature image from an array of point groups
        signaturePad.fromData(data);

        // Draws signature image from an array of point groups, without clearing your existing image (clear defaults to true if not provided)
        signaturePad.fromData(data,  clear: false });


    },  once: true });
}`,
		Call:       t1.SafeScript(`__t1_Init_49d3`, c),
		CallInline: t1.SafeScriptInline(`__t1_Init_49d3`, c),
	}
}
