// Code generated by Tndr(t1) - DO NOT EDIT.

// Tndr(t1): version: v0.0.3

package dirls

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/tndr"
import "context"
import "io"
import "bytes"

import (
	"github.com/senforsce/tndr0cean/router"
	"github.com/senforsce/tndrf1sh/web/layout/v1/meta"
)

func HTMX(cf meta.Config, c *router.Context, folder string, list []File) t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var1 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var1 == nil {
			t1_7745c5c3_Var1 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		var t1_7745c5c3_Var2 = []any{c.Get("cls:OwlComponent")}
		t1_7745c5c3_Err = t1.RenderCSSItems(ctx, t1_7745c5c3_Buffer, t1_7745c5c3_Var2...)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<details class=\"")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1.CSSClasses(t1_7745c5c3_Var2).String()))
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\" open><summary><span>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		var t1_7745c5c3_Var3 string
		t1_7745c5c3_Var3, t1_7745c5c3_Err = t1.JoinStringErrs(folder)
		if t1_7745c5c3_Err != nil {
			return t1.Error{Err: t1_7745c5c3_Err, FileName: `owl/dirLs/ls.t1`, Line: 10, Col: 17}
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var3))
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</span></summary><ul>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		for i := range list {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<li>")
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
			if !list[i].isDir {
				var t1_7745c5c3_Var4 = []any{c.Get("cls:file-tree").(string)}
				t1_7745c5c3_Err = t1.RenderCSSItems(ctx, t1_7745c5c3_Buffer, t1_7745c5c3_Var4...)
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<a class=\"")
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1.CSSClasses(t1_7745c5c3_Var4).String()))
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\" hx-get=\"")
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(c.Get("path:FileOpen").(string) + folder + "/" + list[i].Name))
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\" hx-target=\"")
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(c.Get("ids:fileeditor").(string)))
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\" hx-trigger=\"")
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(c.Get("hx:click").(string)))
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\">")
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				var t1_7745c5c3_Var5 string
				t1_7745c5c3_Var5, t1_7745c5c3_Err = t1.JoinStringErrs(list[i].Name)
				if t1_7745c5c3_Err != nil {
					return t1.Error{Err: t1_7745c5c3_Err, FileName: `owl/dirLs/ls.t1`, Line: 21, Col: 21}
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var5))
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</a>")
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
			} else {
				var t1_7745c5c3_Var6 = []any{c.Get("cls:file-tree").(string)}
				t1_7745c5c3_Err = t1.RenderCSSItems(ctx, t1_7745c5c3_Buffer, t1_7745c5c3_Var6...)
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<a class=\"")
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1.CSSClasses(t1_7745c5c3_Var6).String()))
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\" hx-get=\"")
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(c.Get("path:DirLs").(string) + "/" + list[i].Name))
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\" hx-trigger=\"")
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(c.Get("hx:click").(string)))
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\" hx-swap=\"")
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(c.Get("hx:SwapOuterHTML").(string)))
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\">")
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				var t1_7745c5c3_Var7 string
				t1_7745c5c3_Var7, t1_7745c5c3_Err = t1.JoinStringErrs(list[i].Name)
				if t1_7745c5c3_Err != nil {
					return t1.Error{Err: t1_7745c5c3_Err, FileName: `owl/dirLs/ls.t1`, Line: 28, Col: 21}
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var7))
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</a>")
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
			}
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</li>")
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</ul></details>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		t1_7745c5c3_Err = meta.O8(cf).Render(ctx, t1_7745c5c3_Buffer)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}
