PREFIX :     <http://senforsce.com/o8/brain/>
PREFIX mj:   <http://senforsce.com/o8/brain/coach-mj/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sen:  <http://senforsce.com/o8/brain/>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
    <%s>
        rdf:type           mj:UserPayable , owl:NamedIndividual;
        sen:belongsToUser  <%s> .

    <%s>
        rdf:type                     owl:NamedIndividual , sen:PayableCoachMJServiceCredit;
        sen:creditsBelongToPayable   <%s>;
        sen:creditsBelongsToService  mj:ServiceProgrammePersonnalise;
        sen:creditsBelongsToUser     <%s>;
        sen:hasCreditNumberValue     "%s"^^xsd:integer;
        sen:isValidFrom              "%s"^^xsd:dateTime;
        sen:isValidUntil             "%s"^^xsd:dateTime .
}
