
PREFIX :     <http://senforsce.com/o8/brain/>
PREFIX mj:   <http://senforsce.com/o8/brain/coach-mj/>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sen:  <http://senforsce.com/o8/brain/>

DELETE { ?ex ?p ?o }
INSERT  {
    ?ex
        rdf:type                      owl:NamedIndividual , sen:SportMovementExercise;
        sen:ExerciseName              "%s";
        sen:MoveExerciceLastTimeDate  "2025-07-02";
        sen:MoveExercicePRBest        "%s"^^xsd:decimal;
        sen:MoveExercicePRLast        "%s"^^xsd:decimal;
        sen:MoveExercicePRMin         "%s"^^xsd:decimal;
        sen:MoveExercicePRUnit        "%s";
        sen:MoveExerciceReps          "%s"^^xsd:decimal;
        sen:MoveExerciceSets          "%s"^^xsd:decimal;
        sen:MoveExerciceTimeUnit      "%s";
        sen:MoveExerciceWeight        "%s"^^xsd:decimal;
        sen:MoveExerciceWeightUnit    "%s";
        sen:MoveExerciseTime          "%s"^^xsd:decimal;
        sen:hasSportMovement          <%s> .
} WHERE {
    BIND(<%s> AS ?ex)
    ?ex ?p ?o .
}