package main

import (
	"github.com/senforsce/tndr0cean/router"
)

func WithO8MJ(a *router.Tndr0cean) error {
	a.S("cls:OwlComponent", "OwlComponent")
	a.S("cls:SaveSignature", "SaveSignature")
	a.S("cls:abdoulsyLogo", "abdoulsyLogo")
	a.S("cls:componentPreview", "componentPreview")
	a.S("cls:container", "container")
	a.S("cls:controls", "controls")

	a.S("cls:header", "header")
	a.S("cls:message", "message")
	a.S("cls:meta", "meta")
	a.S("cls:metaContents", "metaContents")
	a.S("cls:multiPayloadElement", "multiPayloadElement")
	a.S("cls:noComponentWrapper", "noComponentWrapper")
	a.S("cls:nocomponent", "nocomponent")

	a.S("cls:toolbelt", "toolbelt")
	a.S("hx:ChangeThrottleHalfSecond", `"change throttle:0.5s"`)
	a.S("hx:Click", "click")
	a.S("hx:ScenePayload", "ScenePayload")
	a.S("hx:SwapOuterHTML", "outerHTML")
	a.S("hx:click", "click")
	a.S("hx:componentTreeSwap", `"innerHTML show:#component-tree:top"`)
	a.S("hx:load", "load")
	a.S("i18n:Cancel", "Cancel")
	a.S("i18n:ComingSoon", "Coming Soon")
	a.S("i18n:ComponentsCTA", "View")
	a.S("i18n:Config", "Config")
	a.S("i18n:Dashboard", "Dashboard")
	a.S("i18n:ExploreOntology", "Explore Ontology")
	a.S("i18n:FindInFile", "Find in file")
	a.S("i18n:GoToFile", "Go to file")
	a.S("i18n:Home", "Home")
	a.S("i18n:Save", "Save")
	a.S("i18n:Close", "❌")

	a.S("path:WasmExecJs", "/static/wasm_exec.js")
	a.S("role:controls", "controls")
	a.S("role:navigation", "navigation")
	// layout.t1
	a.S("se:HTMXUrl", "https://unpkg.com/htmx.org@1.9.10")
	a.S("sen:Thunderf1shAppName", "Thunderf1sh")
	a.S("sen:Thunderf1shAppVersion", "v0.0.1")
	a.S("cmj:MarketingPageTitle", "Coach Mj | %s")
	a.S("se:JQueryJSURL", "https://code.jquery.com/jquery-3.4.1.min.js")
	a.S("se:BootstrapJSURL", "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js")
	a.S("se:WoWJSURL", "/static/lib/wow/wow.min.js")
	a.S("se:EasingJSURL", "/static/lib/easing/easing.min.js")
	a.S("se:WaypointsJSURL", "/static/lib/waypoints/waypoints.min.js")
	a.S("se:CounterupJSURL", "/static/lib/counterup/counterup.min.js")
	a.S("se:OWLCarouselJSURL", "/static/lib/owlcarousel/owl.carousel.min.js")
	a.S("se:MomentJSURL", "/static/lib/tempusdominus/js/moment.min.js")
	a.S("se:MomentTimezoneJSURL", "/static/lib/tempusdominus/js/moment-timezone.min.js")
	a.S("se:TempusDominusJSURL", "/static/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js")
	a.S("se:MainJSURL", "/static/js/main.js")
	a.S("se:PreconnectGoogleFontsApiURL", "https://fonts.googleapis.com")
	a.S("se:PreconnectGStaticFontsURL", "https://fonts.gstatic.com")
	a.S("se:OpenSansFontCSSURL", "https://fonts.googleapis.com/css2?family=Chakra+Petch:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Handjet:wght@100..900&family=Oooh+Baby&family=Pixelify+Sans:wght@400..700&family=Press+Start+2P&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap")
	a.S("se:FontAwesomeCSSURL", "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css")
	a.S("se:BootstrapIconsCSSURL", "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css")
	a.S("se:AnimateCSSLibraryCSSFilePath", "/static/lib/animate/animate.min.css")
	a.S("se:OWLCSSLibraryCSSFilePath", "/static/lib/owlcarousel/assets/owl.carousel.min.css")
	a.S("se:TempusDominusLibraryCSSFilePath", "/static/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css")
	a.S("se:BootstrapCSSFilePath", "/static/css/bootstrap.min.css")
	a.S("se:GlobalCSSFilePath", "/static/css/global.css")
	a.S("se:AdminStyleCSSFilePath", "/static/style.css")
	a.S("se:StyleCSSFilePath", "/static/css/style.css")
	a.S("se:AppCSSFilePath", "/static/css/app.css")
	a.S("se:T1GridCSSFilePath", "/static/css/t1grid.css")

	a.S("se:TimelineMinCSSFilePath", "/static/css/timeline.min.css")

	a.S("i18n:Dashboard", "Coach-MJ | Panneau de Controle")
	a.S("i18n:AboutPageTitle", "Appellez-moi Coach MJ.")
	a.S("i18n:AboutPageTitlePill", "Qui suis-je ?")
	a.S("i18n:KnowMore", "En savoir plus")
	a.S("path:KnowMore", "/values")
	a.S("i18n:AboutQuote", "“… Car après tout, nous sommes tous l’artisan du plus beau des projets, Notre Vie.”")
	a.S("path:AboutCoachMJLogoImg", "/static/img/coach.png")
	a.S("mj:Timeline1Title", "Janvier à Mars 2024")
	a.S("mj:Timeline1Text", "<p>Coach stagiaire chez <b>« SILVATICUS  CROSSFIT »</b></p>")
	a.S("mj:Timeline2Title", "Mars 2024")
	a.S("mj:Timeline2Text", "<p>CQP Instructeur Fitness, INSED FITNESS SCHOOL</p>")
	a.S("mj:Timeline3Title", "Depuis Avril 2024")
	a.S("mj:Timeline3Text", "<ul><li>Coach cours collectifs à l’APHP</li><li>coaching individuels pour les particuliers</li></ul>")
	a.S("mj:Timeline4Title", "Depuis Juin 2024")
	a.S("mj:Timeline4Text", "<p>Jury auprès de l'INSED FITNESS SCHOOL pour CQPIF</p>")
	a.S("mj:Timeline5Title", "Décembre 2024")
	a.S("mj:Timeline5Text", "<p>Sport Santé: Activité Physique sous prescription médicale, FORMA’</p>")
	a.S("i18n:AboutSectionTitlePill", "COACH MJ")
	a.S("i18n:AboutSectionTitle", "Pourquoi choisir ma méthodologie?")
	a.S("i18n:AboutSectionSubTitle", "Ensemble")
	a.S("i18n:AboutSectionDescription", "Stet no et lorem dolor et diam, amet duo ut dolore vero eos. No stet est diam rebum amet diam ipsum. Clita clita labore, dolor duo nonumy clita sit at, sed sit sanctus dolor eos.")
	a.S("i18n:AboutSectionQuality1", " définirons <span class=txt-primary>vos objectifs</span>")
	a.S("i18n:AboutSectionQuality2", " bâtirons <span class=txt-primary>votre programme </span>")
	a.S("i18n:AboutSectionQuality3", " pérenniserons <span class=txt-primary>vos résultats.</span>")
	a.S("i18n:AboutSectionCTAText", "Lire Plus")
	a.S("i18n:AboutSectionCTAHREF", "/services")
	a.S("path:AboutHeroImageFilePath", "/static/img/maxence.png")
	a.S("i18n:AboutHeroImageAlt", "Coach-MJ")
	a.S("mj:AboutLogoSectionTitlePill", "Coach MJ")
	a.S("i18n:AboutLogoSectionTitle", "Mon Logo!")
	a.S("i18n:AboutLogoSectionDescription", "<b>“J’ai voulu mon logo coloré et multicolore car j’ai l’intime conviction que la vie est une immense toile qu’on remplit chaque jour de teintes différentes. Dans le but de former le portrait de notre histoire”</b>")
	a.S("i18n:AboutLogoSectionDescriptionValues", "Mes valeurs : le Mieux-être, le changement et l’inclusivité car selon moi la guérison, le bonheur et toutes les émotions de ce monde se vivent ensemble et se partagent. Afin de vivre mieux et longtemps vivons ensemble et unis")
	a.S("i18n:AboutLogoSectionCTALabel", "En savoir plus")
	a.S("path:AboutLogoSectionCTAHREF", "/valeurs")
	a.S("path:AboutLogoSectionLogo", "/static/img/logo-transparent.png")
	a.S("i18n:Address", "Adresse")
	a.S("i18n:ContactUs", "Contactez-nous")
	a.S("i18n:SendUsEmail", "Envoyez nous un emai")
	a.S("mj:PhoneNumber", "+33 6 26 38 49 45")
	a.S("mj:EmailAddress", "info@coachmjapa.fr")
	a.S("i18n:ContactFormLabelForName", "Votre Nom(s)")
	a.S("i18n:ContactFormLabelForTelephone", "Téléphone")
	a.S("i18n:ContactFormLabelForMessage", "Méssage")
	a.S("i18n:ContactFormLabelForClientType", "Particulier/Entreprise")
	a.S("i18n:ContactFormLabelForBeginner", "Débutant")
	a.S("i18n:ContactFormLabelForIntermediate", "Intermédiaire")
	a.S("i18n:ContactFormLabelForConfirmed", "Confirmé")
	a.S("i18n:ContactFormLabelForIndividual", "Particulier")
	a.S("i18n:ContactFormLabelForBusiness", "Entreprise")
	a.S("i18n:ContactFormLabelForSportsmansType", "Type de Sportif")
	a.S("i18n:ContactFormSendMessage", "Send Message")
	a.S("i18n:ContactFormWrapperTitle", "Avez-Vous une question ? Contactez-Nous.")
	a.S("i18n:ContactFormWrapperSubTitle", "Formulaire de contact en cours de création")
	a.S("i18n:Services", "Services")
	a.S("i18n:CollectveCourses", "Cours Collectifs")
	a.S("i18n:IndividualCoaching", "Coaching Individuel")
	a.S("i18n:IndividualizedProgramme", "Programme Individualisé")
	a.S("i18n:SportsConsulting", "Consulting Sportif")
	a.S("i18n:APA", "Accompagnement Physique Adapté")
	a.S("i18n:FewLinks", "Liens Utiles")
	a.S("i18n:AboutLabel", "Qui suis-je ?")
	a.S("i18n:MyValues", "Mes Valeurs")
	a.S("i18n:MySubscriptions", "Mes Abonnements")
	a.S("i18n:Support", "Support")

	a.S("i18n:News", "News")
	a.S("i18n:NewsletterInstructions", "Veuillez préciser votre email si vous voulez recevoir les dernières nouvelles par e-mail")
	a.S("i18n:Register", "S'inscrire")
	a.S("i18n:HeaderHero1Title", " - Coaching sportif sur-mesure")
	a.S("i18n:HeaderHero2Title", " - Plan nutritionnel personnalisé")
	a.S("i18n:HeaderHero3Title", " - Accompagnement Physique Adapté (APA)")
	a.S("i18n:HeaderStats1Label", "Accompagnements")
	a.S("i18n:HeaderStats1Value", "30")
	a.S("i18n:HeaderStats2Label", "Clients satisfaits")
	a.S("i18n:HeaderStats2Value", "500")
	a.S("i18n:HeaderStats3Label", "Total Patients")
	a.S("i18n:HeaderStats3Value", "12345")
	a.S("i18n:HeaderCarousel1Label", "Le Mieux Etre")
	a.S("path:HeaderCarousel1Img", "/static/img/mieuxetre.png")
	a.S("i18n:HeaderCarousel2Label", "L'Inclusitivé")
	a.S("path:HeaderCarousel2Img", "/static/img/inclusive.webp")
	a.S("i18n:HeaderCarousel3Label", "Le Changement")
	a.S("path:HeaderCarousel3Img", "/static/img/change.webp")
	a.S("i18n:Home", "Accueil")
	a.S("i18n:About", "Qui suis-je ?")
	a.S("i18n:Values", "Mes Valeurs")
	a.S("i18n:Services", "Services")
	a.S("i18n:Subscriptions", "Abonnements")
	a.S("i18n:Contact", "Contact")
	a.S("path:LogoImgSymbol", "/static/img/coachmj-man.svg")
	a.S("path:LogoImgTitle", "/static/img/coach.svg")
	a.S("i18n:Register", "S'inscrire")
	a.S("path:Home", "/")
	a.S("path:About", "/about")
	a.S("path:Values", "/valeurs")
	a.S("path:Services", "/services")
	a.S("path:Subscriptions", "/abonnement")
	a.S("path:Contact", "/contact")
	a.S("path:Register", "/register")
	a.S("id:Home", "NavHome")
	a.S("id:About", "NavAbout")
	a.S("id:Values", "NavValues")
	a.S("id:Services", "NavServices")
	a.S("id:Subscriptions", "NavSubscriptions")
	a.S("id:Contact", "NavContact")
	a.S("id:Register", "NavRegister")
	a.S("i18n:Values1", "Mieux-être")
	a.S("i18n:Values1Programme", "1h15: Accueil/Echauffement ostéo articulaire, musculaire/ Corps de séance/ retour au calme. Le coaching est toujours adapté à vous, à votre mood du jour et vos envies (après 4 coaching, Coach MJ adaptera au maximum vos exercices préférés). ")
	a.S("i18n:FillForm", "C'est Parti !")
	a.S("i18n:Values2", "Changement")
	a.S("i18n:Values2Programme", "1h15: Le programme  sera détaillé et vous permettra d&apos;atteindre aussi bien vos objectifs qu&apos;en coaching en présentiel. Le coach pourra suivre à distance vos progrès.")
	a.S("i18n:Values3", "Inclusivité")
	a.S("i18n:Values3Programme", "Cet abonnement hybride  s’inscrit dans une dynamique mensuelle et permet d’alterner d’une semaine à l’autre coaching en présentiel et programme individualisé (sans Coach MJ). Chaque mois, les Axes de travail change et permet donc de travailler de façon efficiente sur 6 mois.")
	a.S("i18n:OurValues", "Nos Valeurs")
	a.S("static", "/f/valeurs-coaching-individuel")
	a.S("static", "#valeurs-details .content")
	a.S("static", "valeurs hybride: 2 + 2")
	a.S("i18n:Service1Title", "Cours Collectifs")
	a.S("i18n:Service1Subtitle", "Plus forts ensemble…Je vous propose des cours collectifs : petit (3 personnes maximum) ou grand (10 personnes maximum) groupe, en entreprise, en extérieur ou en salle, tout est possible. ")
	a.S("i18n:Service1Benefits1", "Des programmations sur-mesure & cohérentes")
	a.S("i18n:Service1Benefits2", "Du sport plaisir")
	a.S("i18n:Service1Benefits3", "Des playlists adaptés")
	a.S("i18n:HowTo", "Comment ça se passe ?")
	a.S("i18n:Service1Instructions", "Remplir le formulaire de contact/ Préciser la taille du groupe/Mentionner si il y a un objectif commun/Réception du devis/Validation & signature du contrat/Mise en place du programme avec Coach MJ.")
	a.S("i18n:Service2Title", "Coaching individuel")
	a.S("i18n:Service2Subtitle", "Un objectif en particuliers, une reprise, un lancement… chacun son histoire, chacun son chemin…")
	a.S("i18n:Service2Benefits1", "Le respect de l’objectif fixé: chaque exercice a son importance")
	a.S("i18n:Service2Benefits2", "Une adaptation des coaching: signales tes exercices préférés et tu en auras à volonté")
	a.S("i18n:Service2Benefits3", "De la bonne humeur & de la bienveillance")
	a.S("i18n:Service2Instructions", "Choisir le formulaire à remplir/Programmation d’un RDV (téléphonique, visio ou en présentiel) /Validation & signature du contrat/Mise en place du programme avec Coach MJ/Profites de ton 1er coaching.")
	a.S("i18n:Service3Title", "Programme personnalisé")
	a.S("i18n:Service3Subtitle", "Tu préfères le sport en solo néanmoins soutenu par une programmation de qualité. C’est ce service qu’il te faut..")
	a.S("i18n:Service3Benefits1", "Compréhension du besoin et échanges constructifs autour des objectifs à atteindre")
	a.S("i18n:Service3Benefits2", "Suivi personnalisé des métriques et adaptation des programmes")
	a.S("i18n:Service3Benefits3", "Echange hebdomadaire avec Coach MJ si besoin")
	a.S("i18n:Service3Instructions", "Choisir le formulaire à remplir/Programmation d’un RDV (téléphonique, visio ou en présentiel) /Validation & signature du contrat/Mise en place du programme avec Coach MJ/Profites de ton 1er coaching.")
	a.S("i18n:Service4Title", "Consulting sportif")
	a.S("i18n:Service4Subtitle", "Tu es un professionnel et tu ouvres, équipes, optimises ta salle de sport. Tu es un particuliers et tu souhaites des conseils sur l’acquisition de matériel. Coach MJ peut t’accompagner du choix à la mise en place de ton matériel.")
	a.S("i18n:Service4Instructions", "Choisir le formulaire à remplir/Programmation d’un RDV (téléphonique, visio ou en présentiel) /Validation & signature du contrat/Mise en place du programme avec Coach MJ/Profites de ton 1er coaching.")

	a.S("i18n:Service5Title", "Sport Santé (APA)")
	a.S("i18n:Service5Subtitle", "Parce que “le mieux-être, l’inclusivité et le changement” est mon CREDO et que pour moi le sport santé est ma priorité. Je propose un accompagnement spécifique pour les personnes étant atteintes d’affections longue durée.")
	a.S("i18n:Service5Instructions", "Remplir le formulaire ALD/Programmation d’un RDV (téléphonique, visio ou en présentiel)/Etude du dossier et échange au besoin avec le médecin/spécialiste/ Proposition d’un programme et devis/Validation & signature du contrat/Mise en place du programme avec Coach MJ")

	a.S("i18n:Service6Title", "Coaching nutritionnel")
	a.S("i18n:Service6Subtitle", "Parce que “le mieux-être, l’inclusivité et le changement” est mon CREDO et que pour moi le sport santé est ma priorité. Je propose un accompagnement spécifique pour les personnes étant atteintes d’affections longue durée.")
	a.S("i18n:Service6Instructions", "Remplir le formulaire ALD/Programmation d’un RDV (téléphonique, visio ou en présentiel)/Etude du dossier et échange au besoin avec le médecin/spécialiste/ Proposition d’un programme et devis/Validation & signature du contrat/Mise en place du programme avec Coach MJ")

	a.S("i18n:ServicesSectionTitle", "Nos Services")
	a.S("i18n:Visits", "Visites")
	a.S("i18n:LoadingEn", "Loading...")
	a.S("i18n:Loading", "Chargement...")
	a.S("i18n:Subscription1Title", "ABONNEMENT COACHING INDIVIDUEL EN PRESENTIEL")
	a.S("i18n:Sub6Month", "Engagement 6 mois")
	a.S("i18n:Subscription1Details", "1h15: Accueil/Echauffement ostéo articulaire, musculaire/ Corps de séance/ retour au calme. Le coaching est toujours adapté à vous, à votre mood du jour et vos envies (après 4 coaching, Coach MJ adaptera au maximum vos exercices préférés).")
	a.S("i18n:Subscription2Title", "ABONNEMENT PROGRAMME INDIVIDUALISE")
	a.S("i18n:Subscription2Details", "1h15: Le programme  sera détaillé et vous permettra d&apos;atteindre aussi bien vos objectifs qu&apos;en coaching en présentiel. Le coach pourra suivre à distance vos progrès.")
	a.S("i18n:Subscription3Title", "ABONNEMENT HYBRIDE: 2 COACHING + 2 PROGRAMMES/MOIS")
	a.S("i18n:Subscription3Details", "Cet abonnement hybride  s’inscrit dans une dynamique mensuelle et permet d’alterner d’une semaine à l’autre coaching en présentiel et programme individualisé (sans Coach MJ). Chaque mois, les Axes de travail change et permet donc de travailler de façon efficiente sur 6 mois.")
	a.S("i18n:Subscription4Title", "ABONNEMENT HYBRIDE: 4 COACHING + 4 PROGRAMMES/MOIS")
	a.S("i18n:Subscription4Details", "Un vrai challenge sur 6 mois avec chaque semaine un coaching individuel en présentiel et un programme individualisé à réaliser en autonomie. Résultats garantis sur 6 mois.")
	a.S("i18n:Subscription5Title", "LES 2 SEMAINES D’ESSAI")
	a.S("i18n:Subscription5Details", "Parce que nous sommes tous riches de nos différences alors il est parfois nécessaire d’essayer avant de signer. Voici un pack de 2 semaines d’essai vous permettant d’apprécier le coaching individuel en présentiel et le programme individualisé en autonomie chaque semaine de cet abonnement.")
	a.S("i18n:Subscription6Title", "Pack Débutant")
	a.S("i18n:Subscription6Details", "Le pack débutant contient du matériel (Kettlebel, élastique, haltères) et 4 programmes individualisés pour ceux qui préfèrent s’entrainer en autonomie.")
	a.S("i18n:TeamComponentTitlePill", "Coach MJ")
	a.S("i18n:TeamComponentTitle", "Coach sportif et nutrition")
	a.S("i18n:TeamComponentNameAndAlias", "Maxence JEUDY / Coach MJ")
	a.S("i18n:TeamComponentJobTitle", "CEO and Founder")
	a.S("static", "Témoignages")
	a.S("static", "Que disent nos clients!")
	a.S("static", "Je me sens beaucoup mieux grâce aux séances de coaching de coach-mj, j'aurais jamais imaginé que la méditation ait un effet aussi profond.")
	a.S("static", "Satisfaction globale ")
	a.S("static", "Pédagogie")
	a.S("static", "Fun")
	a.S("static", "Bienveillance")
	a.S("static", "/static/img/testimonial-2.jpg")
	a.S("static", "Île-de-France")
	a.S("static", "Lundi - Vendredi : 09.00 - 21.00")
	a.S("static", "06 16 40 36 72")
	a.S("static", "https://www.facebook.com/profile.php?id=61570489165681")
	a.S("static", "Mangas")
	a.S("static", "Jeux vidéos")
	a.S("static", "Poésie")
	a.S("static", "Sciences")
	a.S("static", "Animaux")
	a.S("static", "Empatique")
	a.S("static", "Pédagogue")
	a.S("static", "Original")
	a.S("static", "Pugnacité")
	a.S("static", "Créativité")
	a.S("static", "Adaptabilité")
	a.S("static", "#modedevie")
	a.S("static", "#direction")
	a.S("static", "#pharedanslanuit")
	a.S("static", "#mieuxêtre")
	a.S("static", "Injustice")
	a.S("static", "Solitude")
	a.S("static", "Irrespect")
	a.S("static", "Exclusion")
	a.S("static", "Valeurs")
	a.S("static", "Nos Valeurs")
	a.S("static", "Instructeurs")
	a.S("static", "Experts")
	a.S("static", "Services")
	a.S("static", "de Qualité")
	a.S("static", "Positive")
	a.S("static", "Consultation")
	a.S("static", "24 Hours")
	a.S("i18n:Contacts", "Contacts")

	a.S("i18n:LegalMentions", "Mentions légales")
	a.S("i18n:ConfidencialityPolicy", "Politique de confidentialité")
	a.S("i18n:Sitemap", "Plan du site")
	a.S("mj:JobProposition", "Coach sportif &amp; nutrition")
	a.S("mj:JobAdditional", "Sport Santé")
	a.S("static", "static")
	a.S("lang", "fr")

	return nil
}
