package main

import (
	"github.com/senforsce/tndr0cean/router"
)

func WithBootstrap(a *router.Tndr0cean) error {
	a.S("cls:app", `"app"`)
	a.S("cls:spinner", `"spinner"`)
	a.S("cls:navLink", `"nav-item nav-link"`)

	a.S("cls:ServiceComponent", `"serviceComponent container py-5"`)

	a.S("cls:pageContainer", `"page-container"`)
	a.S("cls:adminFooter", `"bdT ta-c p-30 lh-0 fsz-sm c-grey-600"`)
	a.S("cls:baseLayout", `"baseLayout"`)
	a.S("cls:backToTop", `"btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top"`)
	a.S("cls:arrowUp", `"bi bi-arrow-up"`)
	a.S("cls:AboutSectionComponent", `"AboutSectionComponent container-fluid py-5"`)
	a.S("cls:container", `"container"`)
	a.S("cls:containerFluid", `"container-fluid"`)

	a.S("cls:LogoImgSymbol", `"LogoImgSymbol"`)
	a.S("cls:LogoImgTitle", `"LogoImgTitle"`)

	a.S("cls:rowG5", `"row g5"`)
	a.S("cls:fadeIn", `"wow fadeIn"`)

	a.S("cls:fadeInHalfColumn", `"col-lg-6 wow fadeIn"`)
	a.S("cls:fadeInThirdColumn", `"col-lg-4 wow fadeIn"`)
	a.S("cls:fadeInSpaceColumn", `"col-lg-1 wow fadeIn"`)
	a.S("cls:flexColumn", `"d-flex flex-column"`)
	a.S("cls:titlePill", `"titlePill d-inline-block border rounded-pill py-1 px-4 bg-primary text-white"`)
	a.S("cls:aboutTitlePill", `"AboutTitlePill d-inline-block py-1 text-gray"`)

	a.S("cls:aboutSectionQuality", `"far fa-check-circle text-primary me-3"`)
	a.S("cls:aboutSectionCTA", `"aboutSectionCTA text-white btn btn-primary rounded-pill py-2 px-3 mt-3"`)
	a.S("cls:aboutSectionImg1", `"aboutSectionImg1 img-fluid rounded w-75 align-self-end"`)
	a.S("cls:aboutSectionImg2", `"aboutSectionImg2 img-fluid rounded w-50 bg-white pt-3 pe-3"`)
	a.S("cls:AboutHeroComponent", `"AboutHeroComponent full-width py-5"`)
	a.S("cls:AboutLogoComponent", `"AboutLogoComponent pt-5 pb-5"`)
	a.S("cls:CTA", `"CTA btn btn-primary  text-white rounded-pill py-1 px-3 mt-3"`)

	a.S("cls:AboutQuoteComponent", `"AboutQuoteComponent full-width overflow-hidden my-5 px-lg-0"`)
	a.S("cls:AboutQuoteTextContainer", `"AboutQuoteTextContainer py-5 wow fadeIn"`)
	a.S("cls:AboutQuoteTextWrapper", `"AboutQuoteTextWrapper p-lg-5 ps-lg-0"`)
	a.S("cls:AboutQuoteText", `"AboutQuoteText mb-4 pb-2"`)
	a.S("cls:AboutQuoteImageContainer", `"AboutQuoteImageContainer  pe-lg-0 wow fadeIn"`)
	a.S("cls:AboutQuoteImageWrapper", `"AboutQuoteImageWrapper position-relative h-100"`)
	a.S("cls:AboutQuoteImage", `"AboutQuoteImage position-absolute img-fluid"`)
	a.S("cls:AboutQuoteGroup", `"AboutQuoteGroup row g-0 mx-lg-0"`)
	a.S("cls:AboutQuoteGroupContainer", `"AboutQuoteGroupContainer px-lg-0"`)
	a.S("cls:ContactPillWrapper", `"ContactPillWrapper h-100 bg-light rounded d-flex align-items-center p-5"`)
	a.S("cls:ContactPillIconWrapper", `"ContactPillIconWrapper d-flex flex-shrink-0 align-items-center justify-content-center rounded-circle bg-white"`)
	a.S("cls:ContactPillIconPhone", `"ContactPillIconPhone fa fa-phone-alt text-primary"`)
	a.S("cls:ContactPillIconEnveloppe", `"ContactPillIconEnveloppe fa fa-envelope-open text-primary"`)
	a.S("cls:ContactTitlePill", `"d-inline-block border rounded-pill py-1 px-4"`)
	a.S("cls:FeatureComponent", `"FeatureComponent container-fluid txt-primary overflow-hidden my-5 px-lg-0"`)
	a.S("cls:FeatureComponentTitlePill", `"FeatureComponentTitlePill d-inline-block border rounded-pill txt-primary py-1 px-4"`)
	a.S("cls:FooterComponent", `"FooterComponent container-fluid text-light footer wow fadeIn"`)
	a.S("cls:FooterLink", `"btn btn-link text-light"`)
	a.S("cls:FooterSocialIconWrapper", `"btn btn-outline-light btn-social rounded-circle"`)
	a.S("cls:FooterColumn", `"col-lg-4 col-md-4"`)
	a.S("cls:AboutVibeListComponent", `"AboutVibeListComponent mt-5 ml-5 wow fadeIn"`)
	a.S("cls:AboutVibeListItemsWrapper", `"AboutVibeListItemsWrapper d-flex"`)

	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)
	a.S("static", `"static"`)

	return nil
}
