package main

import (
	"github.com/senforsce/tndr0cean/router"
)

func WithO8(app *router.Tndr0cean) error {
	app.S("cls:OwlComponent", "OwlComponent")
	app.S("cls:SaveSignature", "SaveSignature")
	app.S("cls:abdoulsyLogo", "abdoulsyLogo")
	app.S("cls:componentPreview", "componentPreview")
	app.S("cls:container", "container")
	app.S("cls:controls", "controls")
	app.S("cls:dirloader", "dirloader")
	app.S("cls:fe", "fe")
	app.S("cls:file-tree", "file-tree")
	app.S("cls:header", "header")
	app.S("cls:icon-holder", "icon-holder")
	app.S("cls:message", "message")
	app.S("cls:meta", "meta")
	app.S("cls:metaContents", "metaContents")
	app.S("cls:multiPayloadElement", "multiPayloadElement")
	app.S("cls:noComponentWrapper", "noComponentWrapper")
	app.S("cls:nocomponent", "nocomponent")
	app.S("cls:scene-active", "scene-active")
	app.S("cls:secondary-nav", "secondary-nav")
	app.S("cls:toolbelt", "toolbelt")
	app.S("hx:ChangeThrottleHalfSecond", "change throttle:0.5s")
	app.S("hx:Click", "click")
	app.S("hx:ScenePayload", "ScenePayload")
	app.S("hx:SwapOuterHTML", "outerHTML")
	app.S("hx:click", "click")
	app.S("hx:componentTreeSwap", "innerHTML show:#component-tree:top")
	app.S("hx:load", "load")
	app.S("i18n:Cancel", "Cancel")
	app.S("i18n:ComingSoon", "Coming Soon")
	app.S("i18n:ComponentsCTA", "View")
	app.S("i18n:Config", "Config")
	app.S("i18n:Dashboard", "Dashboard")
	app.S("i18n:ExploreOntology", "Explore Ontology")
	app.S("i18n:FindInFile", "Find in file")
	app.S("i18n:GoToFile", "Go to file")
	app.S("i18n:Home", "Home")
	app.S("i18n:Save", "Save")
	app.S("i18n:SceneInstructions", "Select a component on the sidebar to display it.")
	app.S("i18n:ShowAllCommands", "Show all commands")
	app.S("i18n:ShowSettings", "Show Settings")
	app.S("i18n:WelcomeMessage", "Welcome to Thunderf1sh !")
	app.S("i18n:WelcomeSubMessage", "Part of the Tndr Suite From Senforsce.")
	app.S("id:CurrentComponent", "CurrentComponent")
	app.S("id:CurrentIntegrations", "CurrentIntegrations")
	app.S("id:SaveSignature", "SaveSignature")
	app.S("id:Signature", "Signature")
	app.S("id:SignaturePadScid", "::SignatureForm")
	app.S("id:editor", "editor")
	app.S("id:fileeditor", "fileeditor")
	app.S("id:fileeditorTrigger", "fileeditorTrigger")
	app.S("id:host", "host")
	app.S("id:metaContents", "metaContents")
	app.S("id:scene-active", "scene-active")
	app.S("id:sceneTrigger", "sceneTrigger")
	app.S("ids:component-tree", "#component-tree")
	app.S("ids:fileeditor", "#fileeditor")
	app.S("ids:metaContents", "#metaContents")
	app.S("ids:scene-active", "#scene-active")
	app.S("path:Components", "/components")
	app.S("path:CurrentComponent", "/owl/current")
	app.S("path:DirLs", "/owl")
	app.S("path:FileEdit", "/file/edit")
	app.S("path:FileOpen", "/file/open")
	app.S("path:MainWasm", "main.wasm")
	app.S("path:Root", "/")
	app.S("path:SignaturePad", "https://cdn.jsdelivr.net/npm/signature_pad@4.0.0/dist/signature_pad.umd.min.js")
	app.S("path:WasmExecJs", "/static/wasm_exec.js")
	app.S("role:controls", "controls")
	app.S("role:navigation", "navigation")
	app.S("se:AceJsCDNURL", "https://cdn.jsdelivr.net/npm/ace-builds@1.32.5/src-min-noconflict/ace.js")
	app.S("se:AceJsThemeCDNURL", "https://cdn.jsdelivr.net/npm/ace-builds@1.32.5/src-min-noconflict/theme-dracula.min.js")
	app.S("se:HTMXUrl", "https://unpkg.com/htmx.org@1.9.10")
	app.S("sen:Thunderf1shAppName", "Thunderf1sh")
	app.S("sen:Thunderf1shAppVersion", "v0.0.1")
	app.S("sen:Thunderf1shPageTitle", "Thunderf1sh | %s")

	//temporary TODO inject from .go file
	app.S("path:SparQlCurrentServer", "/sparql/current-server")
	app.S("path:SparQlCurrentUser", "/sparql/current-user")
	app.S("path:SparQlCurrentIntegrations", "/sparql/current-integrations")
	app.S("path:SparQlCurrentComponent", "/sparql/current-component")

	return nil
}
